# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet
disqus: louismoresi
#google_analytics: dbyll

redcarpet:
  extensions: [ "fenced_code_blocks",
                "hard_wrap",
                "autolink",
                "tables",
                "strikethrough",
                "with_toc_data",
                "highlight",
                "prettify",
                "no_intra_emphasis"]

excerpt_separator: "\n\n"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Teaching Related Software and Resources
author:
  name: Louis Moresi
  img_url: "blank"
  email: louis.moresi@unimelb.edu.au
  github: lmoresi
  twitter: louismoresi
  pinterest:
  linkedin: louis-moresi
  bio:  Professor of Geophysics, University of Melbourne
  email_md5:

rss_path:        feed.xml
categories_path: categories.html
tags_path:       tags.html

BASE_PATH: github.moresi.info/tutorial
